import Link from "next/link";
import AppShell from "../../components/AppShell";
import { evidence, expression, formatPct, summary, trials } from "../../lib/evidence";

export default function LabPage() {
  const state = summary();
  const [trial8] = trials();
  const budget = evidence<any>("SEARCH_BUDGET.json");
  const capabilities = evidence<any>("CAPABILITY_REGISTRY.json");
  return <AppShell active="Lab">
    <section className="hero"><div><p className="eyebrow">AUTONOMOUS RESEARCH CONTROL ROOM</p><h1>The system said no.</h1><p className="thesis">{state.truth_line}</p></div><div className="state-lock"><span>RESEARCH STATUS</span><strong>DISCOVERY CLOSED</strong><small>{state.protocol} · immutable evidence snapshot</small></div></section>
    <div className="notice"><strong>{state.discovery_status}</strong> · {state.discovery_reason}</div>
    <section className="stat-grid" aria-label="Final research counts"><div><strong>{state.trials}</strong><span>COMMITTED TRIALS</span></div><div><strong>{state.candidates}</strong><span>CANDIDATE</span></div><div><strong>{state.certified}</strong><span>CERTIFIED</span></div><div><strong>{state.paper_eligible}</strong><span>PAPER ELIGIBLE</span></div></section>
    <h2 className="section-title">LATEST CONTROLLED BATCH · TWO PRE-REGISTERED SLOTS</h2>
    <section className="trial-grid">
      <article className="panel trial-card"><div className="panel-head"><span>TRIAL 8 · BETA RESIDUAL</span><b className="verdict fail">REJECTED</b></div><div className="panel-body"><p className="label">EXECUTABLE HYPOTHESIS</p><p>{trial8.executable_hypothesis}</p>{trial8.semantic_lint.length > 0 && <p className="mismatch">RATIONALE / RECIPE MISMATCH</p>}<p className="label">QWEN RATIONALE · PRESERVED</p><p className="muted">{trial8.qwen_rationale}</p><code>{expression((trial8.compiled as any)?.signal)}</code><dl className="compact-dl"><div><dt>Symbols</dt><dd>RAMDUSDT / RQQQUSDT</dd></div><div><dt>First hard fail</dt><dd>Stability</dd></div><div><dt>DSR</dt><dd>{formatPct(trial8.dsr?.probability)} / 90% required</dd></div><div><dt>Permutation p</dt><dd>0.2029 · FAIL</dd></div><div><dt>OOS fills</dt><dd>0 · INCONCLUSIVE</dd></div><div><dt>Lifecycle</dt><dd>ABANDON</dd></div></dl><Link className="text-link" href="/factors/trial-8">Inspect complete evidence →</Link></div></article>
      <article className="panel trial-card"><div className="panel-head"><span>TRIAL 9 · SESSION TRANSITION</span><b className="verdict fail">REJECTED</b></div><div className="panel-body"><p className="label">STRUCTURAL RESULT</p><h3>Repair refused before HTTP.</h3><p className="muted">The first response was structurally invalid. The conservative reservation system projected that a repair would breach the frozen 14,000-token phase ceiling.</p><div className="reason-code">NO_RUN_PROJECTED_BUDGET_EXHAUSTED_AFTER_INVALID_OUTPUT</div><dl className="compact-dl"><div><dt>First hard fail</dt><dd>Syntax</dd></div><div><dt>Valid recipe</dt><dd>Unavailable</dd></div><div><dt>Compiled AST</dt><dd>Not run</dd></div><div><dt>Anchor metrics</dt><dd>Not run</dd></div><div><dt>Paper impact</dt><dd>None</dd></div></dl><Link className="text-link" href="/factors/trial-9">Inspect refusal evidence →</Link></div></article>
    </section>
    <section className="workspace top-gap"><article className="panel"><div className="panel-head"><span>TRIAL 8 · DETERMINISTIC GATE STACK</span><span>NO MISSING RESULT IS GREEN</span></div>{trial8.gates.map(gate => <div className="gate" key={gate.name}><div><strong>{gate.name}</strong><p>{gate.reason}</p></div><span className={`verdict ${gate.outcome.toLowerCase().replace(" ", "-")}`}>{gate.outcome}</span></div>)}</article><article className="panel"><div className="panel-head"><span>SEARCH CONTROL</span><span>FROZEN</span></div><div className="panel-body"><div className="large-number">9</div><p className="label">GLOBAL COMMITTED SEARCH N</p><p>Every committed hypothesis raises the statistical hurdle for the next one.</p><dl className="compact-dl"><div><dt>Measured / charged</dt><dd>{budget.measured_tokens_total.toLocaleString()} tokens</dd></div><div><dt>Hard phase budget</dt><dd>{budget.hard_limit.toLocaleString()} tokens</dd></div><div><dt>Blocked request</dt><dd>1 repair</dd></div><div><dt>Duplicate proposals</dt><dd>0 in FDP-v3</dd></div><div><dt>Protocols used</dt><dd>3</dd></div></dl></div></article></section>
    <section className="panel top-gap"><div className="panel-head"><span>RESEARCH COMPILER</span><span>MODEL OUTPUT IS NOT EXECUTABLE CODE</span></div><div className="card-grid"><div><p className="label">CONTRACT</p><h3>{capabilities.recipe_schema}</h3><p>Qwen emits bounded recipes. Deterministic code alone emits safe FactorSpec ASTs.</p></div><div><p className="label">COMPILER</p><h3>{capabilities.compiler_version}</h3><p>Same canonical recipe, same recipe hash, same AST.</p></div><div><p className="label">READY FAMILIES</p><h3>{capabilities.ready_families.join(" · ")}</h3><p>All unsupported families remain hidden from proposal prompts.</p></div><div><p className="label">ANCHOR CONTRACT</p><h3>session-transition-v1 · 15m</h3><p>Exact New York boundaries; missing anchors fail closed.</p></div></div></section>
    <footer><span>CACHED EVIDENCE SNAPSHOT · {new Date(state.generated_at).toISOString()}</span><Link href="/proof">Open 30-second proof →</Link></footer>
  </AppShell>;
}
