import { notFound } from "next/navigation";
import Link from "next/link";
import { expressionText, pct, readPhase2 } from "../../../lib/phase2";

export function generateStaticParams() { return readPhase2().factors.filter((factor) => factor.factor_version_id).map((factor) => ({ id: factor.factor_version_id! })); }

export default async function FactorPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = readPhase2();
  const factor = data.factors.find((item) => item.factor_version_id === id);
  if (!factor || !factor.metrics_json || !factor.canonical_spec_json) notFound();
  const report = factor.metrics_json;
  return <div className="app-shell"><aside className="rail"><Link className="brand" href="/lab">R/</Link><nav><Link href="/lab">Lab</Link><Link className="active" href="/factors">Factors</Link><span>Paper</span><span>Ledger</span><span>System</span></nav></aside><main><header className="system-strip"><span>RESEARCH PROOF</span><span>TRIAL {factor.trial_number}</span><span>{data.protocol}</span><strong>{factor.lifecycle_state}</strong></header><section className="hero compact"><div><p className="eyebrow">FACTOR {factor.canonical_identity_hash.slice(0, 12)}</p><h1>{factor.name}</h1><p className="thesis">{factor.thesis}</p></div></section><section className="workspace"><article className="panel hypothesis"><div className="panel-head"><span>SAFE EXPRESSION</span><span>{factor.canonical_spec_json.session_filter.join(" · ")}</span></div><code>{expressionText(factor.canonical_spec_json.signal)}</code><dl className="contract"><div><dt>Universe</dt><dd>{factor.canonical_spec_json.universe.join(" · ")}</dd></div><div><dt>Historical window</dt><dd>{report.data_contract.start} → {report.data_contract.end}</dd></div><div><dt>OOS boundary</dt><dd>{report.split_timestamp}</dd></div><div><dt>Cost model</dt><dd>{report.data_contract.cost_model_version}</dd></div><div><dt>Dataset hash</dt><dd>{report.dataset_hash}</dd></div><div><dt>Report hash</dt><dd>{factor.report_hash}</dd></div></dl></article><article className="panel gates"><div className="panel-head"><span>GATE STACK</span><span>{report.aggregate}</span></div>{factor.gates.map((gate) => <div className="gate" key={gate.name}><div><strong>{gate.name}</strong><p>{gate.reason}</p></div><span className={`verdict ${gate.outcome.toLowerCase()}`}>{gate.outcome}</span></div>)}</article></section><section className="panel metrics"><div className="panel-head"><span>HISTORICAL METRICS</span><span>NOT FORWARD PERFORMANCE</span></div><div className="metric-grid"><div><span>Gross</span><strong>{pct(report.metrics.gross.total_return)}</strong></div><div><span>Net</span><strong>{pct(report.metrics.net.total_return)}</strong></div><div><span>IS net</span><strong>{pct(report.metrics.is_net.total_return)}</strong></div><div><span>OOS net</span><strong>{pct(report.metrics.oos_net.total_return)}</strong></div><div><span>OOS fills</span><strong>{report.metrics.oos_net.fills}</strong></div><div><span>Drawdown</span><strong>{pct(report.metrics.net.max_drawdown)}</strong></div></div></section><footer><Link href="/factors">← Back to Graveyard</Link><a href="/evidence/phase2-summary.json">Raw proof JSON ↗</a></footer></main></div>;
}
